# Generated by Django 4.2.4 on 2023-08-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='activated_invite_code',
            field=models.CharField(blank=True, default=None, max_length=6, null=True, verbose_name='Активированный инвайт-код'),
        ),
    ]
