# Generated by Django 4.2.4 on 2023-08-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_alter_profiles_activated_invite_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='patronymic',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='surname',
        ),
        migrations.AlterField(
            model_name='profiles',
            name='phone',
            field=models.CharField(default='+7 (999) 999-99-99', max_length=18, unique=True, verbose_name='Номер телефона'),
        ),
    ]
