# Generated by Django 4.2.4 on 2023-08-17 07:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authen', '0003_remove_profiles_name_remove_profiles_patronymic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthRequests',
            fields=[
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID объекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания объекта')),
                ('auth_code', models.PositiveIntegerField(default=5599, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1000)], verbose_name='Код авторизации')),
                ('django_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Авторизующийся пользователь Django')),
            ],
            options={
                'verbose_name': 'Запрос на авторизацию',
                'verbose_name_plural': 'Запросы на авторизацию',
            },
        ),
    ]
